# Site settings
title: Pallidocs
description: >-
  Pallidocs website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com
navigation:
- name: Films
  nav: 'index/#films'
- name: Forms
  nav: "questions"
- name: Contact
  nav: contact
collections:
  assets:
    title: Assets
    output: true
# Build settings
markdown: kramdown
sass:
  style: full
  sass_dir: css
