# Site settings
title: Pallidocs
description: >-
  Pallidocs website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site, e.g. http://example.com
navigation:
- name: Films
  onClick: moveTo('videos', 20)
- name: Forms
  href: forms
- name: Contact
  href: contact
collections:
  assets:
    title: Assets
    output: true
# Build settings
markdown: kramdown
exclude: ["package.json", "package-lock.json", "node_modules", ".sass-cache"]
