# Site settings
title: Pallidocs
description: >-
  Pallidocs website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pallidocs.netlify.com/" # the base hostname & protocol for your site, e.g. http://example.com
navigation:
- name: Films
  nav: /?films
- name: Reflection
  nav: reflection
- name: Contact
  nav: contact
collections:
  assets:
    title: Assets
    output: true
# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: css
exclude: ["package.json", "package-lock.json", "node_modules", ".sass-cache", "gulpfile.js", "Gemfile", "Gemfile.lock", "readme"]
