---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home page
- type: document
  path: forms.md
  label: Forms page
- type: document
  path: contact.md
  label: Contact page
- type: document
  path: readme.md
  label: Info (private)
  read_only: true
upload_dir: _assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
